mbeck5/GU_Energy_Dashboard

client/app/scripts/controllers/buildingDisplay.js
Also, changed default date range to be more helpful for us until real server is up.
=> Remove better focus area setting

client/app/scripts/controllers/buildingSelector.js, client/app/scripts/services/buildingSvc.js, client/app/styles/buildingSelector.scss, client/app/views/buildingSelector.html, server/controllers/site.js, server/routes.js
Implements dropdown to filter buildings by type.
=> Filter by building type

client/app/index.html, client/app/scripts/controllers/header.js, client/app/views/buildingSelector.html
1) Fix dropdown alignment
2) Toggle navbar dropdown on item click
=> Fixes dawg

client/app/scripts/controllers/buildingSelector.js
Fix for selected buildings not transferring after using search or filter by type.
=> Comparison Fix

client/app/index.html, client/app/scripts/controllers/buildingDisplay.js, client/app/scripts/controllers/buildingSelector.js, client/app/styles/buildingDisplay.scss, client/app/styles/main.scss, client/app/views/buildingDisplay.html
In compare mode, you can now click on the building item rather than only the checkbox to select the building.
The datepickers and toggle no longer retrieve new data immediately upon change.  There is now an apply button to retrieve new data.  Fixes #38 
Other random stuff.
=> Random fixes and stuff

client/app/scripts/controllers/buildingDisplay.js
Removes date slider which allows us to use the interactive guideline feature and tooltips which give the consumption data for all buildings for each point.
=> Remove slider

client/app/scripts/controllers/compDisplay.js, client/app/scripts/services/compEditSvc.js, client/app/views/compDisplay.html, server/controllers/compQuery.js, server/routes.js
cleaned up and commented code
fixed edit check box saves
fixed date formatting
=> edit anomaly fixed

client/app/scripts/controllers/compDisplay.js, client/app/scripts/controllers/competitionGraph.js, client/app/styles/compDisplay.scss, client/app/views/compDisplay.html, server/controllers/compQuery.js
Merge in tabbed view.
Refactoring and fixes.
=> Competition merge

server/controllers/building.js, server/controllers/compQuery.js
Ignore moment deprecations warning for now.  The documentation suggests we are doing everything right and the github issue is unclear on solutions to the problem and future plans of the deprecation.
=> Removed express deprecated methods

client/app/styles/main.scss
Also some adjustments to compatibility warning.
=> L1n3 n33ds b3 Th!ck3r!!!!

client/app/scripts/controllers/frontPageSummary.js, client/app/scripts/services/buildingSvc.js, server/controllers/building.js
Created new queries for the front page graph so that they may look at a specific date instead of just the previous data entered in the database.  getResourcesByType is the query used for the bar graph, and getResourceSum is the query previously used by the pie chart and to be used by the knobs.  To use these new queries just put a date as the second param into the appropriate buildingSvc calls in frontPageSummary
=> New resource sum query

server/app.js
In production mode, database will now point to barney.
=> Production database!

client/app/scripts/controllers/frontPageSummary.js, client/app/scripts/directives/knob.js, client/app/views/buildingSelector.html, client/bower.json, server/app.js
1) go back one more day to ensure data is there
2) block user input for knobs //this for some reason still doesn't work in prod....
3) add knobs as a bower dependency
=> Front graph fixes

client/app/scripts/controllers/buildingDisplay.js, client/app/scripts/controllers/compDisplay.js, client/app/scripts/controllers/frontPageSummary.js, client/app/styles/buildingDisplay.scss, client/app/styles/compDisplay.scss, client/app/views/buildingDisplay.html
Front:
1) Percentages were not being calculated correctly.  Numbers should now be far less egregious.
Display:
1) Detailed Toggle now toggles immediately without need for apply
2) There is now a separator between toggle and date inputs
3) Apply button will now be disabled until dates are changed
Comps:
1) Fix deleting comp on ui #67 
2) On first load, don't select comp if nothing there.  (silences error) 
3) Styling tweaks
=> Misc fixes

client/app/scripts/controllers/buildingDisplay.js, client/app/scripts/controllers/frontPageSummary.js, client/app/views/compDisplay.html
1) round consumption data for building display and front page graphs
2) add elec symbol for each comp entry
=> Misc tweaks

client/app/scripts/controllers/buildingDisplay.js, client/app/views/buildingDisplay.html
Building display:
1) Change 'Done' to 'Close' for date pickers
2) If user enters same date for both 'from' and 'to', the 'to' will automatically increment by one day.
=> Date picker enhancements

client/app/scripts/controllers/buildingDisplay.js
fixes the bug where building name labels are missing because of missing data in comparisions
=> Blank label graph fix

client/app/scripts/controllers/compDisplay.js
=> Improve competition edit reliability

client/app/scripts/controllers/compDisplay.js, client/app/views/compDisplay.html
fixes the lingering top three view
=> fixed lingering top three view

client/app/scripts/app.js, client/app/scripts/controllers/compDisplay.js, client/app/scripts/controllers/competitionGraph.js, client/app/views/compDisplay.html
changed spinner color
added spinner to comps
=> changed spinner color

Maintenance_Plan.md
First draft of the Maintenance Plan.  I did not talk about the database schema as I do not feel qualified, someone else can do that or teach me. @dkaai :smile:  Feel free to make edits!
=> Maintenance Plan d1

client/app/index.html
=> Add some meta data

client/app/styles/buildingDisplay.scss, client/app/views/buildingDisplay.html
=> Fixes the mid size graph

Maintenance_Plan.md
1) Some fixes and elaboration
2) Added deliverables section
3) added navigation to contents
=> Maintenance Plan D2

client/app/scripts/controllers/buildingDisplay.js, client/app/scripts/controllers/buildingSelector.js, client/app/scripts/controllers/compDisplay.js, client/app/scripts/controllers/competitionGraph.js, client/app/scripts/controllers/frontPageSummary.js, client/app/scripts/controllers/header.js
Adds documentation to our controllers.  More should probably be added.  I only commented on stuff that I was familiar with.
=> JS documentation

server/package.json
Removed some things that we weren't using.
=> Authentication

server/app.js, server/controllers/login.js, server/package.json
This may fix the bcrypt issues we are having on the front-end. **bower install**
=> Fix client-side bcrypt?

client/app/scripts/controllers/compDisplay.js, client/app/styles/buildingSelector.scss, client/app/styles/compDisplay.scss, client/app/views/buildingSelector.html, client/app/views/compDisplay.html
1) Always enable Create comp button when logged in
2) various panel resizes
=> UI adjustments

client/app/styles/buildingDisplay.scss, client/app/styles/buildingSelector.scss, client/app/styles/compDisplay.scss, client/app/styles/main.scss, client/app/views/buildingSelector.html
=> Tips scroll bar

client/app/scripts/controllers/compDisplay.js, client/app/scripts/services/compEditSvc.js
=> commented stuff

client/app/scripts/controllers/compDisplay.js, client/app/scripts/controllers/login.js, client/app/styles/compDisplay.scss, client/app/views/compDisplay.html, server/controllers/compQuery.js
Displays username of last person to edit / create competition.
Also, some random cleanup and error silencing.
=> Comps: display editor

client/app/scripts/controllers/competitionGraph.js, client/app/scripts/controllers/frontPageSummary.js, client/app/scripts/controllers/header.js, client/app/scripts/controllers/signup.js, client/app/scripts/controllers/verify.js, server/controllers/building.js, server/controllers/compQuery.js, server/controllers/login.js
I also removed a duplicate function in building.js
=> Added documentation to a bunch of files.
